### ISSUE TITLE
Compatibility with google-cloud-storage gem

### ISSUE THREAD

**Issue by sinergymedia** [kmurph73/google_sheets#4]
Any chance you could update this for compatibilty with google-cloud-storage gem which uses google-api-client v0.33.0? Thanks!

**Comment by kmurph73** [comment]
Sure, will take a look today.

**Comment by sinergymedia** [comment]
Awesome. Appreciate it!

**Comment by kmurph73** [comment]
Ok, updated google-api-client in #5 & pushed that gem update.  Let me know if that solves your issue.

**Comment by sinergymedia** [comment]
Like a charm. Thank you sir!
